version: '3'
services:
  mysql:
    container_name: ebiz-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
    volumes:
      - ../db_init:/docker-entrypoint-initdb.d # Mapowanie lokalnego katalogu ze skryptami inicjalizacyjnymi

  prestashop:
    build:
      context: ./ssl
      dockerfile: Dockerfile
    container_name: prestashop
    image: prestashop/prestashop:1.7.8
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
      - 8443:443
    environment:
      ADMIN_MAIL: admin@prestashop.com 
      ADMIN_PASSWD: admin123
      DB_SERVER: ebiz-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_INSTALL_AUTO: 1
      PS_FOLDER_ADMIN: admin123
    networks:
      - prestashop_network
    volumes:
      - ../prestashop:/var/www/html  # Dane PrestaShop, aby były trwałe

networks:
  prestashop_network:

volumes:
  prestashop:  # Wolumen na dane PrestaShop