version: '3.7'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: prestashop       # Hasło dla root
      MYSQL_DATABASE: prestashop            # Tworzymy bazę danych o nazwie 'prestashop'
    ports:
      - "3307:3306"                          # Mapowanie portów, zewnętrzny 3307 na wewnętrzny 3306
    networks:
      - prestashop-net
    volumes:
      - ./db_data:/var/lib/mysql           # Wolumen bazy danych, zachowa dane nawet po zatrzymaniu kontenera

  prestashop:
    image: prestashop/prestashop:1.7.8-7.3
    container_name: prestashop
    environment:
      DB_SERVER: mariadb                    # Nazwa kontenera MariaDB (nie port)
      DB_NAME: prestashop                   # Nazwa bazy danych, która ma być używana przez PrestaShop
      DB_USER: root                         # Użytkownik bazy danych
      DB_PASSWD: prestashop                 # Hasło dla użytkownika root w MariaDB (musisz ustawić takie samo jak w mariaDB)
      PS_INSTALL_AUTO: 1                    # Automatyczna instalacja PrestaShop
      PS_DOMAIN: localhost:8080            # Adres, pod którym jest dostępny PrestaShop
      PS_FOLDER_ADMIN: admin123     
      ADMIN_MAIL: admin@prestashop.com 
      ADMIN_PASSWD: admin123 # Folder administracyjny PrestaShop
    ports:
      - "8080:80"                           # Mapowanie portów, zewnętrzny 8080 na wewnętrzny 80
    networks:
      - prestashop-net
    depends_on:
      - mariadb
    volumes:
      - ./prestashop:/var/www/html         # Wolumen z plikami PrestaShop

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb                    # Kontener MariaDB, z którym PHPMyAdmin ma się połączyć
      PMA_PORT: 3306                       # Port MariaDB
    ports:
      - "8081:80"                           # Mapowanie portów, zewnętrzny 8081 na wewnętrzny 80
    networks:
      - prestashop-net

networks:
  prestashop-net:  # Definicja sieci, w której działają kontenery

volumes:
  db_data:           # Wolumen do przechowywania danych bazy danych MariaDB
