version: '3'
services:
  mysql:
    container_name: ebiz-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network 

  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:1.7.8
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      ADMIN_MAIL: admin@prestashop.com 
      ADMIN_PASSWD: admin123
      DB_SERVER: ebiz-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost:8080
      PS_FOLDER_ADMIN: admin123
    networks:
      - prestashop_network
    volumes:
      - ./prestashop_data:/var/www/html  

networks:
  prestashop_network:

volumes:
  prestashop_data:  
