<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGiulcxb\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGiulcxb/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGiulcxb.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGiulcxb\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGiulcxb\appProdProjectContainer([
    'container.build_hash' => 'Giulcxb',
    'container.build_id' => '04ef611e',
    'container.build_time' => 1731775903,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGiulcxb');
