<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC7ca0xc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC7ca0xc/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerC7ca0xc.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerC7ca0xc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerC7ca0xc\appProdProjectContainer([
    'container.build_hash' => 'C7ca0xc',
    'container.build_id' => 'fcdf46f4',
    'container.build_time' => 1732477359,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC7ca0xc');
