<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0ecje60\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0ecje60/appProdProjectContainer.php') {
    touch(__DIR__.'/Container0ecje60.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container0ecje60\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container0ecje60\appProdProjectContainer([
    'container.build_hash' => '0ecje60',
    'container.build_id' => 'f3c44adb',
    'container.build_time' => 1731713826,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0ecje60');
