<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOpbbyxh\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOpbbyxh/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerOpbbyxh.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerOpbbyxh\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerOpbbyxh\appProdProjectContainer([
    'container.build_hash' => 'Opbbyxh',
    'container.build_id' => '849c9111',
    'container.build_time' => 1731282082,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOpbbyxh');
