<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXynwkzd\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXynwkzd/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXynwkzd.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXynwkzd\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXynwkzd\appProdProjectContainer([
    'container.build_hash' => 'Xynwkzd',
    'container.build_id' => 'b6f7d638',
    'container.build_time' => 1731701491,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXynwkzd');
