name: CI

on:
  branches:
    - "master"
    - "develop"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: atomowkibe
          password: Admin123123

      - name: Build Docker Image
        run: |
          docker build -f docker_compose/dockerfile -t atomowkibe/prestashop:latest .

      - name: Push Docker Image
        run: |
          docker push atomowkibe/prestashop:latest